model:
  # num_classes: 1
  max_nodes: 600
  encoder_layers: 4
  encoder_attention_heads: 32
  encoder_embed_dim: 512
  encoder_ffn_embed_dim: 512
  attention_dropout: 0.1
  act_dropout: 0.1
  dropout: 0.1
  fingerprint: True
  dist_head: "gbf3d"
  num_dist_head_kernel: 256
  num_edge_types: 16384

training:
  device: "cuda"
  criterion: "l2_loss"
  batch_size: 160
  epochs: 100
  save_interval: 5
  clip_norm: 5.0
  checkpoint_dir: "checkpoints"
  optimizer:
    type: "adam"
    lr: 0.0001
    # end_lr: 1e-09
    weight_decay: 0.00001
  scheduler:
    type: "polynomial_decay"
    warmup_updates: 10
    patience: 10
    power: 1.0
  amp:
    use_amp: False
    scaler_init_scale: 512.0
    scaler_growth_factor: 2.0
    scaler_backoff_factor: 0.5
    scaler_growth_interval: 2000
  flag:
    flag: True
    flag_m: 3
    flag_step_size: 0.001
    flag_mag: 0.01

data:
  num_workers: 4
  # data_buffer_size: 20
  data_dir: "/data/bzeng/Dynaformer/data/boltz"
  processed_dir: "/data/bzeng/Dynaformer/data/processed"
  data_df_path: "/data/bzeng/Dynaformer/data/davis_complete_with_smiles.tsv"
  mmseqs_seq_clus_df_path: "/data/bzeng/Dynaformer/data/davis_complete_id50_cluster.tsv"
  split_method: "wt_mutation"
  split_frac: [0.7, 0.1, 0.2]
  tmp_dir: "/data/bzeng/tmp"